/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MySmiley {}
}

declare global {


  interface HTMLMySmileyElement extends Components.MySmiley, HTMLStencilElement {}
  var HTMLMySmileyElement: {
    prototype: HTMLMySmileyElement;
    new (): HTMLMySmileyElement;
  };
  interface HTMLElementTagNameMap {
    'my-smiley': HTMLMySmileyElement;
  }
}

declare namespace LocalJSX {
  interface MySmiley {}

  interface IntrinsicElements {
    'my-smiley': MySmiley;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-smiley': LocalJSX.MySmiley & JSXBase.HTMLAttributes<HTMLMySmileyElement>;
    }
  }
}


